/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as DownloadIdRouteImport } from './routes/download.$id'
import { Route as BrowseTypeRouteImport } from './routes/browse.$type'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIdRoute = DownloadIdRouteImport.update({
  id: '/download/$id',
  path: '/download/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseTypeRoute = BrowseTypeRouteImport.update({
  id: '/browse/$type',
  path: '/browse/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/browse/$type': typeof BrowseTypeRoute
  '/download/$id': typeof DownloadIdRoute
  '/movie/$id': typeof MovieIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/browse/$type': typeof BrowseTypeRoute
  '/download/$id': typeof DownloadIdRoute
  '/movie/$id': typeof MovieIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/browse/$type': typeof BrowseTypeRoute
  '/download/$id': typeof DownloadIdRoute
  '/movie/$id': typeof MovieIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/watchlist'
    | '/browse/$type'
    | '/download/$id'
    | '/movie/$id'
    | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/watchlist'
    | '/browse/$type'
    | '/download/$id'
    | '/movie/$id'
    | '/watch/$id'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/watchlist'
    | '/browse/$type'
    | '/download/$id'
    | '/movie/$id'
    | '/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  WatchlistRoute: typeof WatchlistRoute
  BrowseTypeRoute: typeof BrowseTypeRoute
  DownloadIdRoute: typeof DownloadIdRoute
  MovieIdRoute: typeof MovieIdRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$id': {
      id: '/download/$id'
      path: '/download/$id'
      fullPath: '/download/$id'
      preLoaderRoute: typeof DownloadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$type': {
      id: '/browse/$type'
      path: '/browse/$type'
      fullPath: '/browse/$type'
      preLoaderRoute: typeof BrowseTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  WatchlistRoute: WatchlistRoute,
  BrowseTypeRoute: BrowseTypeRoute,
  DownloadIdRoute: DownloadIdRoute,
  MovieIdRoute: MovieIdRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
